# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designLogicielFinalV2.ui',
# licensing of 'designLogicielFinalV2.ui' applies.
#
# Created: Sun Aug 18 09:55:33 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1665, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gBGestionNotes = QtWidgets.QGroupBox(self.centralwidget)
        self.gBGestionNotes.setGeometry(QtCore.QRect(400, 20, 521, 641))
        self.gBGestionNotes.setObjectName("gBGestionNotes")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.gBGestionNotes)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 501, 621))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.cBMatiereGBNote = QtWidgets.QComboBox(self.verticalLayoutWidget_9)
        self.cBMatiereGBNote.setObjectName("cBMatiereGBNote")
        self.verticalLayout_5.addWidget(self.cBMatiereGBNote)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lENomNote = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.lENomNote.setObjectName("lENomNote")
        self.verticalLayout_2.addWidget(self.lENomNote)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.lECoeffNote = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.lECoeffNote.setObjectName("lECoeffNote")
        self.verticalLayout_3.addWidget(self.lECoeffNote)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.tWTableNotation = QtWidgets.QTableWidget(self.verticalLayoutWidget_9)
        self.tWTableNotation.setObjectName("tWTableNotation")
        self.tWTableNotation.setColumnCount(2)
        self.tWTableNotation.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tWTableNotation.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tWTableNotation.setHorizontalHeaderItem(1, item)
        self.verticalLayout_9.addWidget(self.tWTableNotation)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pBValiderNotation = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.pBValiderNotation.setObjectName("pBValiderNotation")
        self.horizontalLayout_3.addWidget(self.pBValiderNotation)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.gBMoyBulletin = QtWidgets.QGroupBox(self.centralwidget)
        self.gBMoyBulletin.setGeometry(QtCore.QRect(930, 20, 545, 816))
        self.gBMoyBulletin.setObjectName("gBMoyBulletin")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.gBMoyBulletin)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 531, 621))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.cBEleveBulletin = QtWidgets.QComboBox(self.verticalLayoutWidget_11)
        self.cBEleveBulletin.setObjectName("cBEleveBulletin")
        self.verticalLayout_8.addWidget(self.cBEleveBulletin)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.pBValCalculMoy = QtWidgets.QPushButton(self.verticalLayoutWidget_11)
        self.pBValCalculMoy.setObjectName("pBValCalculMoy")
        self.verticalLayout.addWidget(self.pBValCalculMoy)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.tWBulletin = QtWidgets.QTableWidget(self.verticalLayoutWidget_11)
        self.tWBulletin.setObjectName("tWBulletin")
        self.tWBulletin.setColumnCount(0)
        self.tWBulletin.setRowCount(0)
        self.verticalLayout_11.addWidget(self.tWBulletin)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pBValAppr = QtWidgets.QPushButton(self.verticalLayoutWidget_11)
        self.pBValAppr.setObjectName("pBValAppr")
        self.horizontalLayout_4.addWidget(self.pBValAppr)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_17.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.verticalLayout_17)
        self.labGraphRadar = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labGraphRadar.sizePolicy().hasHeightForWidth())
        self.labGraphRadar.setSizePolicy(sizePolicy)
        self.labGraphRadar.setMinimumSize(QtCore.QSize(400, 0))
        self.labGraphRadar.setObjectName("labGraphRadar")
        self.verticalLayout_11.addWidget(self.labGraphRadar)
        self.gBAjoutAcad = QtWidgets.QGroupBox(self.centralwidget)
        self.gBAjoutAcad.setGeometry(QtCore.QRect(10, 420, 181, 131))
        self.gBAjoutAcad.setObjectName("gBAjoutAcad")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gBAjoutAcad)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.lENomAcad = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lENomAcad.setObjectName("lENomAcad")
        self.verticalLayout_6.addWidget(self.lENomAcad)
        self.pBValNewAcad = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pBValNewAcad.setObjectName("pBValNewAcad")
        self.verticalLayout_6.addWidget(self.pBValNewAcad)
        self.gBAjoutEtab = QtWidgets.QGroupBox(self.centralwidget)
        self.gBAjoutEtab.setGeometry(QtCore.QRect(200, 380, 201, 181))
        self.gBAjoutEtab.setObjectName("gBAjoutEtab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gBAjoutEtab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 160, 160))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.cBListAcad = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cBListAcad.setObjectName("cBListAcad")
        self.verticalLayout_13.addWidget(self.cBListAcad)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_13.addWidget(self.label_3)
        self.lENomEtab = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lENomEtab.setObjectName("lENomEtab")
        self.verticalLayout_13.addWidget(self.lENomEtab)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.lEEtabAdress = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lEEtabAdress.setObjectName("lEEtabAdress")
        self.verticalLayout_13.addWidget(self.lEEtabAdress)
        self.pBValNewEtab = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pBValNewEtab.setObjectName("pBValNewEtab")
        self.verticalLayout_13.addWidget(self.pBValNewEtab)
        self.gBAjoutClasse = QtWidgets.QGroupBox(self.centralwidget)
        self.gBAjoutClasse.setGeometry(QtCore.QRect(10, 560, 181, 271))
        self.gBAjoutClasse.setObjectName("gBAjoutClasse")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gBAjoutClasse)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 160, 250))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.cBListAcadClass = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cBListAcadClass.setObjectName("cBListAcadClass")
        self.verticalLayout_14.addWidget(self.cBListAcadClass)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.cBListEtabClass = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cBListEtabClass.setObjectName("cBListEtabClass")
        self.verticalLayout_14.addWidget(self.cBListEtabClass)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_14.addWidget(self.label_16)
        self.lENomClasse = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lENomClasse.setObjectName("lENomClasse")
        self.verticalLayout_14.addWidget(self.lENomClasse)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_14.addWidget(self.label_23)
        self.lEAnneScol = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lEAnneScol.setObjectName("lEAnneScol")
        self.verticalLayout_14.addWidget(self.lEAnneScol)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_14.addWidget(self.label_24)
        self.lEProfPrinc = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lEProfPrinc.setObjectName("lEProfPrinc")
        self.verticalLayout_14.addWidget(self.lEProfPrinc)
        self.pBValNewClass = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pBValNewClass.setObjectName("pBValNewClass")
        self.verticalLayout_14.addWidget(self.pBValNewClass)
        self.gBAjoutEleve = QtWidgets.QGroupBox(self.centralwidget)
        self.gBAjoutEleve.setGeometry(QtCore.QRect(200, 570, 201, 271))
        self.gBAjoutEleve.setObjectName("gBAjoutEleve")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.gBAjoutEleve)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 160, 250))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_21.addWidget(self.label_18)
        self.cBListAcadEleve = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.cBListAcadEleve.setObjectName("cBListAcadEleve")
        self.verticalLayout_21.addWidget(self.cBListAcadEleve)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_21.addWidget(self.label_19)
        self.cBListEtabEleve = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.cBListEtabEleve.setObjectName("cBListEtabEleve")
        self.verticalLayout_21.addWidget(self.cBListEtabEleve)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_21.addWidget(self.label_21)
        self.cBListClassEleve = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.cBListClassEleve.setObjectName("cBListClassEleve")
        self.verticalLayout_21.addWidget(self.cBListClassEleve)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_21.addWidget(self.label_20)
        self.lENomEleve = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lENomEleve.setObjectName("lENomEleve")
        self.verticalLayout_21.addWidget(self.lENomEleve)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_21.addWidget(self.label_25)
        self.lEPrenomEleve = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lEPrenomEleve.setObjectName("lEPrenomEleve")
        self.verticalLayout_21.addWidget(self.lEPrenomEleve)
        self.pBValNewEleve = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pBValNewEleve.setObjectName("pBValNewEleve")
        self.verticalLayout_21.addWidget(self.pBValNewEleve)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 302, 395))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.cBAcademie = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBAcademie.sizePolicy().hasHeightForWidth())
        self.cBAcademie.setSizePolicy(sizePolicy)
        self.cBAcademie.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cBAcademie.setObjectName("cBAcademie")
        self.verticalLayout_12.addWidget(self.cBAcademie)
        self.cBEtablissement = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBEtablissement.sizePolicy().hasHeightForWidth())
        self.cBEtablissement.setSizePolicy(sizePolicy)
        self.cBEtablissement.setMinimumSize(QtCore.QSize(300, 0))
        self.cBEtablissement.setObjectName("cBEtablissement")
        self.verticalLayout_12.addWidget(self.cBEtablissement)
        self.cBClasse = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBClasse.sizePolicy().hasHeightForWidth())
        self.cBClasse.setSizePolicy(sizePolicy)
        self.cBClasse.setMaximumSize(QtCore.QSize(300, 300))
        self.cBClasse.setObjectName("cBClasse")
        self.verticalLayout_12.addWidget(self.cBClasse)
        self.pBGestNote = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBGestNote.sizePolicy().hasHeightForWidth())
        self.pBGestNote.setSizePolicy(sizePolicy)
        self.pBGestNote.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pBGestNote.setObjectName("pBGestNote")
        self.verticalLayout_12.addWidget(self.pBGestNote)
        self.pBMoyenne = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBMoyenne.sizePolicy().hasHeightForWidth())
        self.pBMoyenne.setSizePolicy(sizePolicy)
        self.pBMoyenne.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pBMoyenne.setObjectName("pBMoyenne")
        self.verticalLayout_12.addWidget(self.pBMoyenne)
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem7)
        self.pBAjoutAcademie = QtWidgets.QPushButton(self.layoutWidget)
        self.pBAjoutAcademie.setAutoFillBackground(False)
        self.pBAjoutAcademie.setObjectName("pBAjoutAcademie")
        self.verticalLayout_15.addWidget(self.pBAjoutAcademie)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem8 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem8)
        self.pBAjoutEtablissement = QtWidgets.QPushButton(self.layoutWidget)
        self.pBAjoutEtablissement.setObjectName("pBAjoutEtablissement")
        self.verticalLayout_16.addWidget(self.pBAjoutEtablissement)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem9 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_18.addItem(spacerItem9)
        self.pBAjoutClasse = QtWidgets.QPushButton(self.layoutWidget)
        self.pBAjoutClasse.setObjectName("pBAjoutClasse")
        self.verticalLayout_18.addWidget(self.pBAjoutClasse)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        spacerItem10 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_20.addItem(spacerItem10)
        self.pBAjoutEleve = QtWidgets.QPushButton(self.layoutWidget)
        self.pBAjoutEleve.setObjectName("pBAjoutEleve")
        self.verticalLayout_20.addWidget(self.pBAjoutEleve)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem11 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_19.addItem(spacerItem11)
        self.pBAjoutMatiere = QtWidgets.QPushButton(self.layoutWidget)
        self.pBAjoutMatiere.setObjectName("pBAjoutMatiere")
        self.verticalLayout_19.addWidget(self.pBAjoutMatiere)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        spacerItem12 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.gBAjoutMat = QtWidgets.QGroupBox(self.centralwidget)
        self.gBAjoutMat.setGeometry(QtCore.QRect(430, 650, 411, 191))
        self.gBAjoutMat.setObjectName("gBAjoutMat")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gBAjoutMat)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 281, 162))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.cBEtabMat = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBEtabMat.sizePolicy().hasHeightForWidth())
        self.cBEtabMat.setSizePolicy(sizePolicy)
        self.cBEtabMat.setObjectName("cBEtabMat")
        self.verticalLayout_7.addWidget(self.cBEtabMat)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.cBAcadMat = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBAcadMat.sizePolicy().hasHeightForWidth())
        self.cBAcadMat.setSizePolicy(sizePolicy)
        self.cBAcadMat.setObjectName("cBAcadMat")
        self.verticalLayout_7.addWidget(self.cBAcadMat)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.lENomMat = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lENomMat.sizePolicy().hasHeightForWidth())
        self.lENomMat.setSizePolicy(sizePolicy)
        self.lENomMat.setObjectName("lENomMat")
        self.verticalLayout_7.addWidget(self.lENomMat)
        self.pBValMat = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pBValMat.setObjectName("pBValMat")
        self.verticalLayout_7.addWidget(self.pBValMat)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_22.addWidget(self.label_26)
        self.cBClassMat = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cBClassMat.setObjectName("cBClassMat")
        self.verticalLayout_22.addWidget(self.cBClassMat)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_22.addWidget(self.label_27)
        self.cBElevMat = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cBElevMat.setObjectName("cBElevMat")
        self.verticalLayout_22.addWidget(self.cBElevMat)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_22.addWidget(self.label_29)
        self.dSBCoeffMat = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.dSBCoeffMat.setObjectName("dSBCoeffMat")
        self.verticalLayout_22.addWidget(self.dSBCoeffMat)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem13)
        self.horizontalLayout_5.addLayout(self.verticalLayout_22)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1665, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.gBGestionNotes.setTitle(QtWidgets.QApplication.translate("MainWindow", "Gestion des Notes", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Gestion des notes", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Noter Devoir", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Matière :", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Nom Devoir :", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Coefficient :", None, -1))
        self.tWTableNotation.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Elève :", None, -1))
        self.tWTableNotation.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Note :", None, -1))
        self.pBValiderNotation.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.gBMoyBulletin.setTitle(QtWidgets.QApplication.translate("MainWindow", "Moyennes - Bulletin", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Moyennes Globales", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Elève :", None, -1))
        self.pBValCalculMoy.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Valider Appréciations Bulletin :", None, -1))
        self.pBValAppr.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.labGraphRadar.setText(QtWidgets.QApplication.translate("MainWindow", "Graphique", None, -1))
        self.gBAjoutAcad.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ajout Académie", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Nom :", None, -1))
        self.pBValNewAcad.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.gBAjoutEtab.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ajout Etablissement", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Académie :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Nom :", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Adresse :", None, -1))
        self.pBValNewEtab.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.gBAjoutClasse.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ajout Classe", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Académie :", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Etablissement :", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Nom :", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Année Scolaire", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Professeur Principal", None, -1))
        self.pBValNewClass.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.gBAjoutEleve.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ajout Elève", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Académie :", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Etablissement :", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Classe :", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Nom :", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Prénom", None, -1))
        self.pBValNewEleve.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "LogiNotes", None, -1))
        self.pBGestNote.setText(QtWidgets.QApplication.translate("MainWindow", "Gestion des notes", None, -1))
        self.pBMoyenne.setText(QtWidgets.QApplication.translate("MainWindow", "Moyennes - Bulletin", None, -1))
        self.pBAjoutAcademie.setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle Académie", None, -1))
        self.pBAjoutEtablissement.setText(QtWidgets.QApplication.translate("MainWindow", "Nouvel Etablissement", None, -1))
        self.pBAjoutClasse.setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle Classe", None, -1))
        self.pBAjoutEleve.setText(QtWidgets.QApplication.translate("MainWindow", "Nouvel Elève", None, -1))
        self.pBAjoutMatiere.setText(QtWidgets.QApplication.translate("MainWindow", "Nouvelle Matière", None, -1))
        self.gBAjoutMat.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ajout Matière", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Etablissement", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Academie", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Nom Matière :", None, -1))
        self.pBValMat.setText(QtWidgets.QApplication.translate("MainWindow", "Valider", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Classe", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Choisir Elève", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "CoefficientMatière :", None, -1))

